spring:
  config:
    name: shop_web
  datasource:
    url: jdbc:postgresql://localhost:5432/OprosDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql:
  main:
    web-application-type: servlet
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

server:
  port: 8081
  servlet:
    session:
      timeout: 20
